In [1]:
import numpy as np
import pandas as pd

In [2]:
file = 'my_workbook.xlsx'

In [8]:
df = pd.read_excel(file)

In [9]:
df

,日期,1 张,2 王,3 李,4 赵,23 粒icing,34村爹看到,此功能,Unnamed: 8
0,NaT,2023-11-11 00:00:00,2023-11-02 00:00:00,2023-10-02 00:00:00,2023-11-14 00:00:00,2023-01-01 00:00:00,2023-11-09 00:00:00,2023-10-30 00:00:00,NaN
1,NaT,病1,病2,病3,病4,病5,病6,病7,NaN
2,2023-11-01,a1,b2,c3,d4,NaN,NaN,NaN,NaN
3,2023-11-02,a2,b3,c4,d5,NaN,NaN,NaN,NaN
4,2023-11-03,a3,b4,c5,d6,NaN,NaN,NaN,NaN
5,2023-11-04,a4,b5,c6,d7,NaN,NaN,NaN,NaN
6,2023-11-05,a5,b6,c7,d8,NaN,NaN,NaN,NaN
7,2023-11-06,a6,b7,c8,d9,NaN,NaN,NaN,NaN
8,2023-11-07,a7,b8,c9,d10,NaN,NaN,NaN,NaN
9,2023-11-08,a8,b9,c10,d11,NaN,NaN,NaN,NaN
10,2023-11-09,a9,b10,c11,d12,NaN,NaN,NaN,NaN
11,2023-11-10,a10,b11,c12,d13,NaN,NaN,NaN,NaN
12,2023-11-11,a11,b12,c13,d14,NaN,NaN,NaN,NaN
13,2023-11-12,a12,b13,c14,d15,NaN,NaN,NaN,NaN
14,2023-11-13,a13,b14,c15,d16,NaN,NaN,NaN,NaN
15,2023-11-14,a14,b15,c16,d17,NaN,NaN,NaN,NaN
16,2023-11-15,a15,b16,c17,d18,NaN,NaN,NaN,NaN
17,2023-11-16,a16,b17,c18,d19,NaN,NaN,NaN,NaN
18,2023-11-17,a17,b18,c19,d20,NaN,NaN,NaN,NaN
19,2023-11-18,a18,b19,c20,d21,NaN,NaN,NaN,NaN
20,2023-11-19,a19,b20,c21,d22,堵车,顶,刺网,NaN
21,2023-11-20,a20,b21,c22,d23,的歌词v,而恶趣,而大方,nnnnnn
22,2023-11-21,a21,b22,c23,d24,cing,eixlcing,eidcewodn,eicnge
23,2023-11-22,a22,b23,c24,d25,NaN,NaN,NaN,NaN

In [10]:
df.shape

(24, 9)